#super user permission
sudo: required
services: 
   - docker
   

before_install:
 - docker build -t sparanid/Docker-python -f Dockerfile.dev .

script:
  - docker run sparanid/Docker-python python mainapp.test.py
