#super user permission
sudo: required
services: 
   - docker
   

before_install:
 - docker build -t sparanid/docker-python -f Dockerfile .

script:
  - docker run sparanid/docker-python python mainapp.test.py

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "dockerpythoncheck"
  env: "dockerpythoncheck-env"
  bucket_name: "elasticbeanstalk-us-east-2-692372411976"
  bucker_path: "dockerpythoncheck"
  on: 
   branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"   
