version: "3"
services:
  mainapp:
      build:
         context: .
         dockerfile:  Dockerfile.dev
      ports : 
         - "8080:5000"
      volumes : 
          - .:/usr/app
           
       
